### ISSUE TITLE
Issues building Viewer and geom samples..

### ISSUE THREAD

**Issue by oscarbg** [seanbaxter/shaders#1]
Hi,
testing using RX Vega on ACO compiler..
note seems bugs are equal as Intel platform.. using Intel branch all samples work..
still:

Viewer sample: can't find brdf.hxx
```
make
[ 50%] Building CXX object CMakeFiles/viewer.dir/viewer.cxx.o
preprocessor: viewer.cxx:17:10
cannot find header brdf.hxx
```

geom sample:
lacks CMakeLists.txt has unuseful CMakeCache.txt
after copying CMakeLists.txt  from cube sample and change source file I get:

make
```
[ 50%] Building CXX object CMakeFiles/cube.dir/geom.cxx.o
error: /home/cosmic/nvidiak/circle/shaders/include/appglfw.hxx:56:32
undeclared identifier 'mat4'
inline void print_matrix(const mat4& m) { 
                               ^

error: /home/cosmic/nvidiak/circle/shaders/include/appglfw.hxx:220:13
undeclared identifier 'camera_t'
inline void camera_t::adjust(float pitch2, float yaw2, float d2) { 
            ^

error: /home/cosmic/nvidiak/circle/shaders/include/appglfw.hxx:298:1
undeclared identifier 'app_t'
app_t::app_t(const char* name, int width, int height) { 
^


```

**Comment by seanbaxter** [comment]
Thanks! Try pulling again and those two missing viewer files will show up as well as the missing CMakeLists.txt for /geom. No idea how they got dropped from the repository.

The mat4 declaration is implicitly done when you use the -shader switch, and since the CMakeLists.txt was missing it wasn't setting it...

**Comment by oscarbg** [comment]
now all samples work.. thanks!
