### ISSUE TITLE
Mesh shading sample?

### ISSUE THREAD

**Issue by oscarbg** [seanbaxter/shaders#2]
Hi,
from documentation seems mesh shading stage (with task shaders) is supported..
would be nice if a simple mesh shading sample could be added for completeness..
thanks..

**Comment by seanbaxter** [comment]
Agreed. I wrote a mesh shader example, but... It won't run in OpenGL, because NVIDIA has decided not to support that feature on OpenGL. I don't have the time or energy to write a Vulkan sample. I looked at using wgpu, which is based on Vulkan, but it only supports vertex, fragment and compute stages.

I need to figure out a way to use Vulkan for testing the compiler and producing samples without letting my productivity go to hell.

**Comment by oscarbg** [comment]
Hi,
sorry but from response isn't clear to me if you mean that NVIDIA doesn't support a cross vendor mesh shader GL ext or that 
GL_NV_mesh_shader extension is buggy on you shaders on current NV drivers..
if it's second case, then it's strange, as even NV extension spec text has recieved some fixes a year after release..
as https://www.khronos.org/registry/OpenGL/extensions/NV/NV_mesh_shader.txt shows:
Last Modified Date:     September 5, 2019
NVIDIA Revision:        5
after original release sometime around September 2018..

In case GL_NV_mesh_shader is buggy I didn't know that and seems you should publish your GL mesh shader samples as it is and ask for bug fixes from Nvidia OpenGL driver team..
for ex. I believe @pixeljetstream @nvpbrown @pdaniell-nv would gladly help getting these issues fixed on Nvidia driver side provided detailed bug reports..

**Comment by pixeljetstream** [comment]
@oscarbg Sean is referring to the lack of mesh shader support as part of the SPIR-V support in OpenGL, those SPIR-V extensions need to be queried separate via GL_ARB_spirv_extensions. And it is true, NVIDIA does not support mesh shaders via SPIR-V in GL, only via plain GLSL. SPIR-V support only exists in Vulkan. It is not something we can easily enable as these drivers use different compiler stacks.

**Comment by oscarbg** [comment]
many thanks for explanation @pixeljetstream !.. makes sense now I had forgot SPIR-V GL path doesn't support extensions like this by default.. sad to hear support for mesh shaders in OGL via GL path is difficult for NV to support..
I will leave the issue open as curious if other IHVs like upcoming AMD 6xxx can support this uses case.. see 1) below for details..
so been thinking a bit more about this, and let me share some related ideas:
1) really curious about AMD, i.e. if upcoming 6xxx series will support mesh shader in GL.. In Vulkan I assume it will be supported either the NV version or a KHR ext similar to how VRS and RT KHR exts have been posted.. of course I'm talking about AMD propietary GL driver which doesn't see much (any?) advancements for years only new product support.. Mesa is another world and I really expect GL mesh shader support on RadeonSI eventually (either NV ext or also a GL_KHR mesh shader version?).. it could be that even Mesa gains GL SPIR-V mesh shader support some day, we will see..
2) as for current NV workarounds around this I'm thinking about two:
a) SPIRV-Cross support for SPV_NV_mesh_shader in GL output.. after all Nsight Graphics is able to show GLSL code of SPIR-V of intercepted Vulkan apps so to me it seems NV has a custom branch of SPIRV-Cross with support for various SPV_NV extensions like raytracing etc.. in that case would be nice if Nvidia could make pull requests to  SPIRV-Cross project with these features.. in that case Circle compiler SPIR-V output could be feed to SPIRV-Cross and resulting output feed as GLSL ..
b) Zink support for mesh shaders: might seem crazy right now but is evolving fast with a custom branch supporting GL 4.6 so apparently even GL_ARB_spirv_extensions..
in that case as Zink translates to Vulkan in theory SPIR-V mesh shaders could be feed up to Vulkan driver avoiding GL limitation.. 
currently Zink is missing support for non Mesa drivers like NV drv and OSes other than linux but situation is changing fast:
upcoming Windows support:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7432

**Comment by seanbaxter** [comment]
I ported a mesh shading sample!
