### ISSUE TITLE
(several questions) Trying to use Circle for Compute shaders

### ISSUE THREAD

**Issue by FROL256** [seanbaxter/shaders#6]
Greetings! I start to use Circle for compiling compute shaders. I have several questions, and would be appreciate for help! 

1) Not sure i did correct with drivers because after i have installed "Vulkan beta driver 455.46.04", my Linux (Linux Mint 20 Cinnamon, linux kernel 5.4.0-62-generic) didn't run as expected (suppose software rendering was enabled), but ... it update driver to 460.32.03. Do you think using 460.32.03 should be ok?

Input C++ (https://drive.google.com/file/d/1BC2h4hNWDxwTzHi1fhKiqHIYwDyASir-/view?usp=sharing) compiles well, but later i got errors from Validation layer (1.2.154.0-1lunarg20.04-2) report errors to me

compiled with futher command line: `./circle -shader -c -emit-spirv demo01.cpp -o demo01.cpp.spv -DUSE_CIRCLE_CC`

2) vkCreateShaderModule -->

UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x555555b17748, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.5 for target environment SPIR-V 1.3 (under Vulkan 1.1 semantics).
    Objects: 1
        [0] 0x555555b17748, type: 3, name: NULL

However shader module itself was created successfully. Assume it is ok.

3) vkCreateComputePipelines fails (with seg-fault) and Validation Layer output is:

VUID-VkPipelineShaderStageCreateInfo-pName-00707(ERROR / SPEC): msgNum: -1282697375 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-pName-00707 ] Object 0: handle = 0x555555b17748, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xb38b9761 | No entrypoint found named `kernel_TestColor` for stage VK_SHADER_STAGE_COMPUTE_BIT.. The Vulkan spec states: pName must be the name of an OpEntryPoint in module with an execution model that matches stage (https://vulkan.lunarg.com/doc/view/1.2.154.0/linux/1.2-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-pName-00707)
    Objects: 1
        [0] 0x555555b17748, type: 3, name: NULL

If dis-asm SPIR-V i have found futher line:
`
OpEntryPoint GLCompute %_Z16kernel_TestColorjjjjjjj "_Z16kernel_TestColorjjjjjjj" %5 %in_hit %out_color %glcomp_GlobalInvocationID
`
Which is strange for me ... 

Well if i try to obtain shader module with kernel with name "_Z16kernel_TestColorjjjjjjj", i don't have Validation Layer error, but vkCreateComputePipelines still catch seg-fault.

4) I tried to remove spec. constants, but situation didn't change.

5) I wonder if it is possible to use specialization constants in CIrcle for setting work group size because i didn't find and example.
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gl_spirv.txt 

`       The built-in vector gl_WorkGroupSize can be specialized using special
         layout local_size_{xyz}_id's applied to the "in" qualifier.  For example:
        layout(local_size_x_id = 18, local_size_z_id = 19) in;
`

Well, this is quite critical issue for me because currently i use clspv and ... this is the ONLY way to set work group size in clspv so my host code is forced to use this way.

I would appreciate for any help or comments, thank you very much!

**Comment by seanbaxter** [comment]
Apologies. I got this issue crossed with another one. Will address this today.

**Comment by seanbaxter** [comment]
Aha. I haven't added support for local_size_{xyz}_id with specialization constants. I didn't even know that feature existed.

It requires some code generation work to associate specialization constants with workgroup size. I'll add it for the next version and let you know when that is pushed.

The other thing is to use Vulkan 1.2. I emit SPIR-V 1.5, and I think Vulkan 1.1 only supports 1.3.

**Comment by seanbaxter** [comment]
@FROL256 I investigated this issue. The WorkgroupSize decoration that glslang emits is fundamentally broken and won't work with the multi-entry module design of Circle. Fortunately, SPIR-V 1.2 (which is supported by Vulkan 1.1) introduces an OpExecutionModeId LocalSizeId, that explicitly associates the constant expression for each dimension with the shader. This is great.

Unfortunately, it's not supported by either OpenGL or Vulkan or glslang and there's no testing for it. I don't know how it got into SPIR-V but not the APIs. I will keep on the Khronos people to add this. It seems like a pretty easy thing for the drivers to support. It's a weird out-of-sync thing.

**Comment by FROL256** [comment]
Sean, thank you very much for the answer. I will try to initialize Vulkan 1.2 and let you know if it help.
I think that for testing purposes i can change my code to eliminate local_size_{xyz}_id  and just hard code work group size to start moving forward. 

But looking forward to the next version!  Thank you very much!

**Comment by FROL256** [comment]
Ok, now i have enabled `applicationInfo.apiVersion = VK_API_VERSION_1_2` and then i got different message from validation layer on vkCreateShaderModule:

UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x555555b16c48, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: OpPhi's incoming basic block <id> 51[%51] is not a predecessor of <id> 112[%112].
  %118 = OpPhi %bool %true %51 %116 %113

UPD: this is both for 110 and 114 builds

**Comment by seanbaxter** [comment]
This appears to be related to loop structurization, which is the one real buggy area I have. It's the most infernal aspect of SPIR-V. Send me the exact files you're building. I should be able to come up with a workaround at the very least. I only need the shader code, not all the Vulkan stuff around it.

**Comment by FROL256** [comment]
https://drive.google.com/file/d/1BC2h4hNWDxwTzHi1fhKiqHIYwDyASir-/view?usp=sharing
`./circle -shader -c -emit-spirv demo01.cpp -o demo01.cpp.spv -DUSE_CIRCLE_CC`

**Comment by seanbaxter** [comment]
It appears I have an issue with returning out of a switch case. This is that structurization sore spot and I'll get started to address it tomorrow. 

Anyways, very simple fix for your stuff:

```cpp
inline uint get_global_id(uint a_dim) {
  return glcomp_GlobalInvocationID[a_dim];
}
```

Just use a vector index instead of a switch there. I have some stashed code that addresses this that I should resurrect. It's really the only part I'll admit is buggy. :)

Also, functions that use SPIR-V variables should be marked inline. It didn't error on your call because you used -c -emit-spirv, but it would error during a normal single-source run.

**Comment by FROL256** [comment]
got i, thanks! my first compute shader in Circle works!
