### ISSUE TITLE
Obfuscated kernel names in SPIR-V

### ISSUE THREAD

**Issue by FROL256** [seanbaxter/shaders#7]
It seems that Circle emit obfuscated shader names in SPIR-V. For example for "kernel_TestColor" in my previous example i should seek for "_Z16kernel_TestColorjjjjjjj". It would be great to disable name obfuscation via some flag (or by default) if possible for Vulkan users.

Thanks!

**Comment by FROL256** [comment]
Strange ... seem it works now with obuscated names also, srry )

**Comment by FROL256** [comment]
No, it does not, sorry again. i took wrong file )

**Comment by seanbaxter** [comment]
You can put in an extern "C" to turn off mangling. I'd suggest that instead of a switch, because I still want to support templates, which would require mangling.

**Comment by FROL256** [comment]
got it, thanks!
